package birra.modelo.dominio;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Campo generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class Campo implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int idCampo;
	private String name;
	private String id;
	private String type;
	private String label;
	private String agrupado;
	private int prioridad;
	private Integer maxlength;
	
	public Campo() {
	}

	public Campo(int idCampo, String name, String id, String type) {
		this.idCampo = idCampo;
		this.name = name;
		this.id = id;
		this.type = type;
	}

	public Campo(int idCampo, String name, String id, String type,
			String label) {
		this.idCampo = idCampo;
		this.name = name;
		this.id = id;
		this.type = type;
		this.label = label;
	}

	public int getIdCampo() {
		return this.idCampo;
	}

	public void setIdCampo(int idCampo) {
		this.idCampo = idCampo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getAgrupado() {
		return agrupado;
	}

	public void setAgrupado(String agrupado) {
		this.agrupado = agrupado;
	}

	public int getPrioridad() {
		return prioridad;
	}

	public void setPrioridad(int prioridad) {
		this.prioridad = prioridad;
	}

	public Integer getMaxlength() {
		return maxlength;
	}

	public void setMaxlength(Integer maxlength) {
		this.maxlength = maxlength;
	}

}
