package birra.modelo.dominio;

// default package
// Generated 02/10/2017 17:19:21 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorianoticia generated by hbm2java
 */
@Entity
@Table(name = "categorianoticia")
public class Categorianoticia implements java.io.Serializable {
	
	
	private Integer idCategoriaNoticia;
	private String descripcion;
	private Set noticias = new HashSet(0);

	public Categorianoticia() {
	}

	public Categorianoticia(String descripcion, Set noticias) {
		this.descripcion = descripcion;
		this.noticias = noticias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCategoriaNoticia", unique = true, nullable = false)
	public Integer getIdCategoriaNoticia() {
		return this.idCategoriaNoticia;
	}

	public void setIdCategoriaNoticia(Integer idCategoriaNoticia) {
		this.idCategoriaNoticia = idCategoriaNoticia;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorianoticia")
	public Set getNoticias() {
		return this.noticias;
	}

	public void setNoticias(Set noticias) {
		this.noticias = noticias;
	}

}
