package birra.modelo.dominio;

// default package
// Generated 28/09/2017 13:55:22 by Hibernate Tools 4.3.1.Final

/**
 * Categorialistado generated by hbm2java
 */
public class Categorialistado implements java.io.Serializable {

	private Integer idCategoriaListado;
	private String descripcion;

	public Categorialistado() {
	}

	public Categorialistado(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getIdCategoriaListado() {
		return this.idCategoriaListado;
	}

	public void setIdCategoriaListado(Integer idCategoriaListado) {
		this.idCategoriaListado = idCategoriaListado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
