package birra.modelo.dominio;
// default package
// Generated 28/09/2017 13:55:22 by Hibernate Tools 4.3.1.Final

/**
 * Categorianoticia generated by hbm2java
 */
public class Categorianoticia implements java.io.Serializable {

	private Integer idCategoriaNoticia;
	private String descripcion;

	public Categorianoticia() {
	}

	public Categorianoticia(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getIdCategoriaNoticia() {
		return this.idCategoriaNoticia;
	}

	public void setIdCategoriaNoticia(Integer idCategoriaNoticia) {
		this.idCategoriaNoticia = idCategoriaNoticia;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
