package birra.modelo.dominio;

// default package
// Generated 02/10/2017 17:19:21 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorialistado generated by hbm2java
 */
@Entity
@Table(name = "categorialistado")
public class Categorialistado implements java.io.Serializable {
	
	private Integer idCategoriaListado;
	private String descripcion;
	private Set clasificados = new HashSet(0);

	public Categorialistado() {
	}

	public Categorialistado(String descripcion, Set clasificados) {
		this.descripcion = descripcion;
		this.clasificados = clasificados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCategoriaListado", unique = true, nullable = false)
	public Integer getIdCategoriaListado() {
		return this.idCategoriaListado;
	}

	public void setIdCategoriaListado(Integer idCategoriaListado) {
		this.idCategoriaListado = idCategoriaListado;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorialistado")
	public Set getClasificados() {
		return this.clasificados;
	}

	public void setClasificados(Set clasificados) {
		this.clasificados = clasificados;
	}

}
