package birra.modelo.dominio;
// default package
// Generated 28/09/2017 13:55:22 by Hibernate Tools 4.3.1.Final

/**
 * Clasificado generated by hbm2java
 */
public class Clasificado implements java.io.Serializable {

	private Integer idClasificado;
	private Categorialistado categorialistado;
	private String nombre;
	private String mail;
	private String telefono;
	private String web;
	private String redesSociales;
	private String direccionMapa;

	public Clasificado() {
	}

	public Clasificado(String nombre, String mail, String telefono, String web, String redesSociales,
			String direccionMapa) {
		this.nombre = nombre;
		this.mail = mail;
		this.telefono = telefono;
		this.web = web;
		this.redesSociales = redesSociales;
		this.direccionMapa = direccionMapa;
	}

	public Integer getIdClasificado() {
		return this.idClasificado;
	}

	public void setIdClasificado(Integer idClasificado) {
		this.idClasificado = idClasificado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public String getRedesSociales() {
		return this.redesSociales;
	}

	public void setRedesSociales(String redesSociales) {
		this.redesSociales = redesSociales;
	}

	public String getDireccionMapa() {
		return this.direccionMapa;
	}

	public void setDireccionMapa(String direccionMapa) {
		this.direccionMapa = direccionMapa;
	}

	public Categorialistado getCategorialistado() {
		return categorialistado;
	}

	public void setCategorialistado(Categorialistado categorialistado) {
		this.categorialistado = categorialistado;
	}

}
