package birra.modelo.dominio;
// default package
// Generated 28/09/2017 13:55:22 by Hibernate Tools 4.3.1.Final

/**
 * Imagen generated by hbm2java
 */
public class Imagen implements java.io.Serializable {

	private Integer idImagen;
	private Noticia noticia;
	private String nombreArchivo;
	private Integer tipoImagen;
	private String mime;
	private Integer tamanio;

	public Imagen() {
	}

	public Imagen(String nombreArchivo, Integer tipoImagen) {
		this.nombreArchivo = nombreArchivo;
		this.tipoImagen = tipoImagen;
	}

	public Integer getIdImagen() {
		return this.idImagen;
	}

	public void setIdImagen(Integer idImagen) {
		this.idImagen = idImagen;
	}
	
	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	public Integer getTipoImagen() {
		return this.tipoImagen;
	}

	public void setTipoImagen(Integer tipoImagen) {
		this.tipoImagen = tipoImagen;
	}

	public Noticia getNoticia() {
		return noticia;
	}

	public void setNoticia(Noticia noticia) {
		this.noticia = noticia;
	}

	public String getMime() {
		return mime;
	}

	public void setMime(String mime) {
		this.mime = mime;
	}

	public Integer getTamanio() {
		return tamanio;
	}

	public void setTamanio(Integer tamanio) {
		this.tamanio = tamanio;
	}

}
