package birra.modelo.dominio;

import java.util.ArrayList;

import javax.mail.MessagingException;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

import birra.modelo.db.HibernateUtil;
import birra.modelo.tipificaciones.IEntidadWorkflow;
import birra.modelo.utiles.Constantes;
import birra.modelo.utiles.Mailer;

// Generated 10/04/2017 16:13:49 by Hibernate Tools 3.4.0.CR1

/**
 * Mail generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class Mail implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int idAccion;
	
	@OneToOne(mappedBy="mail")
	private Accion accion;
	private String destinatarios;
	private String cuerpo;
	private String asunto;

	public Mail() {
	}

	public Mail(Accion accion, String destinatarios) {
		this.accion = accion;
		this.destinatarios = destinatarios;
	}

	public Mail(Accion accion, String destinatarios, String cuerpo,
			String asunto) {
		this.accion = accion;
		this.destinatarios = destinatarios;
		this.cuerpo = cuerpo;
		this.asunto = asunto;
	}
	
	//Esta la idea, falta poder probarlo.
	public void ejecutar(ArrayList<IEntidadWorkflow> objPersistibles) throws MessagingException {
		birra.modelo.utiles.Mail m = new birra.modelo.utiles.Mail();
		
		//m.agregarDestinatario(this.getDestinatarios());		
		m.setRemitente("web@inti.gob.ar");		
		
		
		String campo = "";
		String valor = "";
		String cuerpoFinal = getCuerpo();
		String asuntoFinal = getAsunto();
		String destinatariosFinal = getDestinatarios();
		
		//Tomo el primero objeto de las entidades porque se que es un pedido, esto habria que verlo
		Pedido p = (Pedido) objPersistibles.get(0);
		
		// me traigo el pedido completo para usar todo lo que necesite en los mails
		String consulta ="select distinct p"
					+ " From Pedido p"
					+ " join fetch p.estado est "
					+ " join fetch p.tipoPedidoWeb tpw"
					+ " left join fetch p.tecnicoAsignado ta"
					+ " join fetch p.agenteSolicitante ae"
					+ " join fetch ae.dependenciaByIdDependenciaOper depOp"
					+ " join fetch depOp.centroCosto cc"
					+ " left join fetch p.logs lg"
					+ " left join fetch lg.agente alg"
					+ " left join fetch p.responsable responsable"					
					+ " where p.idPedido = :idPedido";
		
		p = (Pedido) HibernateUtil.getSessionFactory().getCurrentSession().
				createQuery(consulta).
				setParameter("idPedido", p.getIdPedido()).
				uniqueResult();	
		
		//Reemplazo los valores dinamicos tanto en el cuerpo como en el asunto del mensaje
		while (cuerpoFinal.indexOf("${")!=-1){
			int ini = cuerpoFinal.indexOf("${")+2;
			int fin = cuerpoFinal.indexOf("}",cuerpoFinal.indexOf("${"));			
			
			campo = cuerpoFinal.substring(ini, fin);
			
			valor = p.getCampo(campo);
			cuerpoFinal = cuerpoFinal.substring(0, ini-2)+valor+cuerpoFinal.substring(fin+1, cuerpoFinal.length());
		}
		
		while (asuntoFinal.indexOf("${")!=-1){
			int ini = asuntoFinal.indexOf("${")+2;
			int fin = asuntoFinal.indexOf("}",asuntoFinal.indexOf("${"));			
			
			campo = asuntoFinal.substring(ini, fin);
			
			valor = p.getCampo(campo);
			asuntoFinal = asuntoFinal.substring(0, ini-2)+valor+asuntoFinal.substring(fin+1, asuntoFinal.length());
		}
		
		while (destinatariosFinal.indexOf("${")!=-1){
			int ini = destinatariosFinal.indexOf("${")+2;
			int fin = destinatariosFinal.indexOf("}",destinatariosFinal.indexOf("${"));			
			
			campo = destinatariosFinal.substring(ini, fin);
			
			valor = p.getCampo(campo)+"@inti.gob.ar";
			destinatariosFinal = destinatariosFinal.substring(0, ini-2)+valor+destinatariosFinal.substring(fin+1, destinatariosFinal.length());
		}
		
		m.agregarDestinatario(destinatariosFinal);
		m.setMensaje(cuerpoFinal);	
		m.setAsunto(asuntoFinal);	
		Mailer.enviarMensajeHTML(m);
		
	}

	public int getIdAccion() {
		return this.idAccion;
	}

	public void setIdAccion(int idAccion) {
		this.idAccion = idAccion;
	}

	public Accion getAccion() {
		return this.accion;
	}

	public void setAccion(Accion accion) {
		this.accion = accion;
	}

	public String getDestinatarios() {
		return this.destinatarios;
	}

	public void setDestinatarios(String destinatarios) {
		this.destinatarios = destinatarios;
	}

	public String getCuerpo() {
		return this.cuerpo;
	}

	public void setCuerpo(String cuerpo) {
		this.cuerpo = cuerpo;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

}
