package birra.modelo.dominio;
// default package
// Generated 28/09/2017 13:55:22 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Noticia generated by hbm2java
 */
public class Noticia implements java.io.Serializable {

	private Integer idNoticia;
	private Categorianoticia categorianoticia;
	private String titulo;
	private String copete;
	private String autor;
	private Date fecha;
	private String cuerpo;

	public Noticia() {
	}

	public Noticia(String titulo, String copete, String autor, Date fecha, String cuerpo) {
		this.titulo = titulo;
		this.copete = copete;
		this.autor = autor;
		this.fecha = fecha;
		this.cuerpo = cuerpo;
	}

	public Integer getIdNoticia() {
		return this.idNoticia;
	}

	public void setIdNoticia(Integer idNoticia) {
		this.idNoticia = idNoticia;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getCopete() {
		return this.copete;
	}

	public void setCopete(String copete) {
		this.copete = copete;
	}

	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getCuerpo() {
		return this.cuerpo;
	}

	public void setCuerpo(String cuerpo) {
		this.cuerpo = cuerpo;
	}

	public Categorianoticia getCategorianoticia() {
		return categorianoticia;
	}

	public void setCategorianoticia(Categorianoticia categorianoticia) {
		this.categorianoticia = categorianoticia;
	}

}
