package birra.modelo.dominio;

// default package
// Generated 02/10/2017 17:46:00 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import birra.modelo.tipificaciones.IPersistible;

/**
 * Sponsor generated by hbm2java
 */
@Entity
@Table(name = "sponsor")
public class Sponsor implements java.io.Serializable, IPersistible {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer idSponsor;
	private String nombre;
	private String link;
	private String linkGoogleMaps;
	private String direccion;
	private String descripcion;
	private String telefono;
	private String mail;
	private String linkFacebook;
	private String linkTwitter;
	private String linkWeb;

	public Sponsor() {
	}

	public Sponsor(String nombre, String link, String linkGoogleMaps, String direccion, String descripcion,
			String telefono, String mail, String linkFacebook, String linkTwitter, String linkWeb) {
		this.nombre = nombre;
		this.link = link;
		this.linkGoogleMaps = linkGoogleMaps;
		this.direccion = direccion;
		this.descripcion = descripcion;
		this.telefono = telefono;
		this.mail = mail;
		this.linkFacebook = linkFacebook;
		this.linkTwitter = linkTwitter;
		this.linkWeb = linkWeb;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSponsor", unique = true, nullable = false)
	public Integer getIdSponsor() {
		return this.idSponsor;
	}

	public void setIdSponsor(Integer idSponsor) {
		this.idSponsor = idSponsor;
	}

	@Column(name = "nombre", length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "link", length = 200)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "linkGoogleMaps", length = 200)
	public String getLinkGoogleMaps() {
		return this.linkGoogleMaps;
	}

	public void setLinkGoogleMaps(String linkGoogleMaps) {
		this.linkGoogleMaps = linkGoogleMaps;
	}

	@Column(name = "direccion", length = 600)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "descripcion", length = 2000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "telefono", length = 100)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "mail", length = 100)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "linkFacebook", length = 150)
	public String getLinkFacebook() {
		return this.linkFacebook;
	}

	public void setLinkFacebook(String linkFacebook) {
		this.linkFacebook = linkFacebook;
	}

	@Column(name = "linkTwitter", length = 150)
	public String getLinkTwitter() {
		return this.linkTwitter;
	}

	public void setLinkTwitter(String linkTwitter) {
		this.linkTwitter = linkTwitter;
	}

	@Column(name = "linkWeb", length = 150)
	public String getLinkWeb() {
		return this.linkWeb;
	}

	public void setLinkWeb(String linkWeb) {
		this.linkWeb = linkWeb;
	}

}
