package birra.modelo.dominioInterno;

// Generated 19/07/2017 10:20:55 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Art generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ART", schema = "dbo", catalog = "rrhh")
public class Art implements java.io.Serializable {

	private int idArt;
	private String descripcion;
	private Set<Agente> agentes = new HashSet<Agente>(0);

	public Art() {
	}

	public Art(int idArt) {
		this.idArt = idArt;
	}

	public Art(int idArt, String descripcion, Set<Agente> agentes) {
		this.idArt = idArt;
		this.descripcion = descripcion;
		this.agentes = agentes;
	}

	@Id
	@Column(name = "idART", unique = true, nullable = false)
	public int getIdArt() {
		return this.idArt;
	}

	public void setIdArt(int idArt) {
		this.idArt = idArt;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(targetEntity = Agente.class, fetch = FetchType.LAZY, mappedBy = "art")
	public Set<Agente> getAgentes() {
		return this.agentes;
	}

	public void setAgentes(Set<Agente> agentes) {
		this.agentes = agentes;
	}

}
