package birra.modelo.dominioInterno;

// Generated 19/07/2017 10:20:55 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CambioSituacion generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "CambioSituacion", schema = "dbo", catalog = "rrhh")
public class CambioSituacion implements java.io.Serializable {

	private int idCambioSituacion;
	private String descripcion;
	private Set<Log> logs = new HashSet<Log>(0);

	public CambioSituacion() {
	}

	public CambioSituacion(int idCambioSituacion) {
		this.idCambioSituacion = idCambioSituacion;
	}

	public CambioSituacion(int idCambioSituacion, String descripcion, Set<Log> logs) {
		this.idCambioSituacion = idCambioSituacion;
		this.descripcion = descripcion;
		this.logs = logs;
	}

	@Id
	@Column(name = "idCambioSituacion", unique = true, nullable = false)
	public int getIdCambioSituacion() {
		return this.idCambioSituacion;
	}

	public void setIdCambioSituacion(int idCambioSituacion) {
		this.idCambioSituacion = idCambioSituacion;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cambioSituacion")
	public Set<Log> getLogs() {
		return this.logs;
	}

	public void setLogs(Set<Log> logs) {
		this.logs = logs;
	}

}
