package birra.modelo.dominioInterno;

import java.util.ArrayList;

// Generated 19/07/2017 10:20:55 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Especialidad generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Especialidad", schema = "dbo", catalog = "rrhh")
public class Especialidad implements java.io.Serializable {

	private int idEspecialidad;
	private String descripcion;
	private Integer idTipoSituacion;
	private List<Agente> agentes = new ArrayList<Agente>();

	public Especialidad() {
	}

	public Especialidad(int idEspecialidad, String descripcion) {
		this.idEspecialidad = idEspecialidad;
		this.descripcion = descripcion;
	}

	public Especialidad(int idEspecialidad, String descripcion,
			Integer idTipoSituacion, List<Agente> agentes) {
		this.idEspecialidad = idEspecialidad;
		this.descripcion = descripcion;
		this.idTipoSituacion = idTipoSituacion;
		this.agentes = agentes;
	}

	@Id
	@Column(name = "idEspecialidad", unique = true, nullable = false)
	public int getIdEspecialidad() {
		return this.idEspecialidad;
	}

	public void setIdEspecialidad(int idEspecialidad) {
		this.idEspecialidad = idEspecialidad;
	}

	@Column(name = "descripcion", nullable = false, length = 300)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "idTipoSituacion")
	public Integer getIdTipoSituacion() {
		return this.idTipoSituacion;
	}

	public void setIdTipoSituacion(Integer idTipoSituacion) {
		this.idTipoSituacion = idTipoSituacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "especialidad")
	public List<Agente> getAgentes() {
		return this.agentes;
	}

	public void setAgentes(List<Agente> agentes) {
		this.agentes = agentes;
	}

}
