package birra.modelo.dominioInterno;

// Generated 19/07/2017 10:20:55 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Log", schema = "dbo", catalog = "rrhh")
public class Log implements java.io.Serializable {

	private int idLog;
	private MotivoBaja motivoBaja;
	private CambioSituacion cambioSituacion;
	private TipoMovimiento tipoMovimiento;
	private Situacion situacionByIdSituacionFinal;
	private Situacion situacionByIdSituacionInicial;
	private Agente agente;
	private Date fechaOperacion;
	private Date fechaMovimiento;
	private Date fechaFinContrato;

	public Log() {
	}

	public Log(int idLog, TipoMovimiento tipoMovimiento, Agente agente,
			Date fechaOperacion, Date fechaMovimiento) {
		this.idLog = idLog;
		this.tipoMovimiento = tipoMovimiento;
		this.agente = agente;
		this.fechaOperacion = fechaOperacion;
		this.fechaMovimiento = fechaMovimiento;
	}

	public Log(int idLog, MotivoBaja motivoBaja,
			CambioSituacion cambioSituacion, TipoMovimiento tipoMovimiento,
			Situacion situacionByIdSituacionFinal,
			Situacion situacionByIdSituacionInicial, Agente agente,
			Date fechaOperacion, Date fechaMovimiento, Date fechaFinContrato) {
		this.idLog = idLog;
		this.motivoBaja = motivoBaja;
		this.cambioSituacion = cambioSituacion;
		this.tipoMovimiento = tipoMovimiento;
		this.situacionByIdSituacionFinal = situacionByIdSituacionFinal;
		this.situacionByIdSituacionInicial = situacionByIdSituacionInicial;
		this.agente = agente;
		this.fechaOperacion = fechaOperacion;
		this.fechaMovimiento = fechaMovimiento;
		this.fechaFinContrato = fechaFinContrato;
	}

	@Id
	@Column(name = "idLog", unique = true, nullable = false)
	public int getIdLog() {
		return this.idLog;
	}

	public void setIdLog(int idLog) {
		this.idLog = idLog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMotivoBaja")
	public MotivoBaja getMotivoBaja() {
		return this.motivoBaja;
	}

	public void setMotivoBaja(MotivoBaja motivoBaja) {
		this.motivoBaja = motivoBaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCambioSituacion")
	public CambioSituacion getCambioSituacion() {
		return this.cambioSituacion;
	}

	public void setCambioSituacion(CambioSituacion cambioSituacion) {
		this.cambioSituacion = cambioSituacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoMovimiento", nullable = false)
	public TipoMovimiento getTipoMovimiento() {
		return this.tipoMovimiento;
	}

	public void setTipoMovimiento(TipoMovimiento tipoMovimiento) {
		this.tipoMovimiento = tipoMovimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSituacionFinal")
	public Situacion getSituacionByIdSituacionFinal() {
		return this.situacionByIdSituacionFinal;
	}

	public void setSituacionByIdSituacionFinal(
			Situacion situacionByIdSituacionFinal) {
		this.situacionByIdSituacionFinal = situacionByIdSituacionFinal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSituacionInicial")
	public Situacion getSituacionByIdSituacionInicial() {
		return this.situacionByIdSituacionInicial;
	}

	public void setSituacionByIdSituacionInicial(
			Situacion situacionByIdSituacionInicial) {
		this.situacionByIdSituacionInicial = situacionByIdSituacionInicial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "legajo", nullable = false)
	public Agente getAgente() {
		return this.agente;
	}

	public void setAgente(Agente agente) {
		this.agente = agente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaOperacion", nullable = false, length = 23)
	public Date getFechaOperacion() {
		return this.fechaOperacion;
	}

	public void setFechaOperacion(Date fechaOperacion) {
		this.fechaOperacion = fechaOperacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaMovimiento", nullable = false, length = 23)
	public Date getFechaMovimiento() {
		return this.fechaMovimiento;
	}

	public void setFechaMovimiento(Date fechaMovimiento) {
		this.fechaMovimiento = fechaMovimiento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaFinContrato", length = 23)
	public Date getFechaFinContrato() {
		return this.fechaFinContrato;
	}

	public void setFechaFinContrato(Date fechaFinContrato) {
		this.fechaFinContrato = fechaFinContrato;
	}

}
