package birra.modelo.dominioInterno;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lugar generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Lugar", schema = "dbo", catalog = "rrhh")
public class Lugar implements java.io.Serializable {

	private int idLugar;
	private String descripcion;
	private List<Dependencia> dependencias = new ArrayList<Dependencia>();

	public Lugar() {
	}

	public Lugar(int idLugar, String descripcion) {
		this.idLugar = idLugar;
		this.descripcion = descripcion;
	}

	public Lugar(int idLugar, String descripcion, List<Dependencia> dependencias) {
		this.idLugar = idLugar;
		this.descripcion = descripcion;
		this.dependencias = dependencias;
	}

	@Id
	@Column(name = "idLugar", unique = true, nullable = false)
	public int getIdLugar() {
		return this.idLugar;
	}

	public void setIdLugar(int idLugar) {
		this.idLugar = idLugar;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugar")
	public List<Dependencia> getDependencias() {
		return this.dependencias;
	}

	public void setDependencias(List<Dependencia> dependencias) {
		this.dependencias = dependencias;
	}

}
