package birra.modelo.dominioInterno;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MotivoBaja generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "MotivoBaja", schema = "dbo", catalog = "rrhh")
public class MotivoBaja implements java.io.Serializable {

	private int idMotivoBaja;
	private String descripcion;
	private List<Log> logs = new ArrayList<Log>();

	public MotivoBaja() {
	}

	public MotivoBaja(int idMotivoBaja, String descripcion) {
		this.idMotivoBaja = idMotivoBaja;
		this.descripcion = descripcion;
	}

	public MotivoBaja(int idMotivoBaja, String descripcion, List<Log> logs) {
		this.idMotivoBaja = idMotivoBaja;
		this.descripcion = descripcion;
		this.logs = logs;
	}

	@Id
	@Column(name = "idMotivoBaja", unique = true, nullable = false)
	public int getIdMotivoBaja() {
		return this.idMotivoBaja;
	}

	public void setIdMotivoBaja(int idMotivoBaja) {
		this.idMotivoBaja = idMotivoBaja;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motivoBaja")
	public List<Log> getLogs() {
		return this.logs;
	}

	public void setLogs(List<Log> logs) {
		this.logs = logs;
	}

}
