package birra.modelo.dominioInterno;

import java.util.ArrayList;

// Generated 19/07/2017 10:20:55 by Hibernate Tools 3.4.0.CR1

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NivelEducacion generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "NivelEducacion", schema = "dbo", catalog = "rrhh")
public class NivelEducacion implements java.io.Serializable {

	private int idNivelEducacion;
	private String descripcion;
	private List<Agente> agentes = new ArrayList<Agente>();

	public NivelEducacion() {
	}

	public NivelEducacion(int idNivelEducacion, String descripcion) {
		this.idNivelEducacion = idNivelEducacion;
		this.descripcion = descripcion;
	}

	public NivelEducacion(int idNivelEducacion, String descripcion, List<Agente> agentes) {
		this.idNivelEducacion = idNivelEducacion;
		this.descripcion = descripcion;
		this.agentes = agentes;
	}

	@Id
	@Column(name = "idNivelEducacion", unique = true, nullable = false)
	public int getIdNivelEducacion() {
		return this.idNivelEducacion;
	}

	public void setIdNivelEducacion(int idNivelEducacion) {
		this.idNivelEducacion = idNivelEducacion;
	}

	@Column(name = "descripcion", nullable = false, length = 300)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelEducacion")
	public List<Agente> getAgentes() {
		return this.agentes;
	}

	public void setAgentes(List<Agente> agentes) {
		this.agentes = agentes;
	}

}
