package birra.modelo.dominioInterno;

import java.util.ArrayList;

// Generated 19/07/2017 10:20:55 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NivelDependencia generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "NivelDependencia", schema = "dbo", catalog = "rrhh")
public class NivelDependencia implements java.io.Serializable {

	private int idNivelDependencia;
	private String descripcion;
	private int nivel;
	private List<Dependencia> dependencias = new ArrayList<Dependencia>();

	public NivelDependencia() {
	}

	public NivelDependencia(int idNivelDependencia, String descripcion,
			int nivel) {
		this.idNivelDependencia = idNivelDependencia;
		this.descripcion = descripcion;
		this.nivel = nivel;
	}

	public NivelDependencia(int idNivelDependencia, String descripcion,
			int nivel, List<Dependencia> dependencias) {
		this.idNivelDependencia = idNivelDependencia;
		this.descripcion = descripcion;
		this.nivel = nivel;
		this.dependencias = dependencias;
	}

	@Id
	@Column(name = "idNivelDependencia", unique = true, nullable = false)
	public int getIdNivelDependencia() {
		return this.idNivelDependencia;
	}

	public void setIdNivelDependencia(int idNivelDependencia) {
		this.idNivelDependencia = idNivelDependencia;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "nivel", nullable = false)
	public int getNivel() {
		return this.nivel;
	}

	public void setNivel(int nivel) {
		this.nivel = nivel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelDependencia")
	public List<Dependencia> getDependencias() {
		return this.dependencias;
	}

	public void setDependencias(List<Dependencia> dependencias) {
		this.dependencias = dependencias;
	}

}
