package birra.modelo.dominioInterno;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nivel generated by hbm2java
 */
@SuppressWarnings({ "serial" })
@Entity
@Table(name = "Nivel", schema = "dbo", catalog = "rrhh")
public class Nivel implements java.io.Serializable {

	private int idNivel;
	private String descripcion;
	private List<Agente> agentes = new ArrayList<Agente>();

	public Nivel() {
	}

	public Nivel(int idNivel) {
		this.idNivel = idNivel;
	}

	public Nivel(int idNivel, String descripcion, List<Agente> agentes) {
		this.idNivel = idNivel;
		this.descripcion = descripcion;
		this.agentes = agentes;
	}

	@Id
	@Column(name = "idNivel", unique = true, nullable = false)
	public int getIdNivel() {
		return this.idNivel;
	}

	public void setIdNivel(int idNivel) {
		this.idNivel = idNivel;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivel")
	public List<Agente> getAgentes() {
		return this.agentes;
	}

	public void setAgentes(List<Agente> agentes) {
		this.agentes = agentes;
	}

}
