package birra.modelo.dominioInterno;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Situacion generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Situacion", schema = "dbo", catalog = "rrhh")
public class Situacion implements java.io.Serializable {

	private int idSituacion;
	private TipoSituacion tipoSituacion;
	private String descripcion;
	private String sigla;
	private Integer idTipoContrato;
	private List<Log> logsForIdSituacionFinal = new ArrayList<Log>();
	private List<Agente> agentes = new ArrayList<Agente>();
	private List<Log> logsForIdSituacionInicial = new ArrayList<Log>();

	public Situacion() {
	}

	public Situacion(int idSituacion) {
		this.idSituacion = idSituacion;
	}

	public Situacion(int idSituacion, TipoSituacion tipoSituacion,
			String descripcion, String sigla, Integer idTipoContrato,
			List<Log> logsForIdSituacionFinal, List<Agente> agentes,
			List<Log> logsForIdSituacionInicial) {
		this.idSituacion = idSituacion;
		this.tipoSituacion = tipoSituacion;
		this.descripcion = descripcion;
		this.sigla = sigla;
		this.idTipoContrato = idTipoContrato;
		this.logsForIdSituacionFinal = logsForIdSituacionFinal;
		this.agentes = agentes;
		this.logsForIdSituacionInicial = logsForIdSituacionInicial;
	}

	@Id
	@Column(name = "idSituacion", unique = true, nullable = false)
	public int getIdSituacion() {
		return this.idSituacion;
	}

	public void setIdSituacion(int idSituacion) {
		this.idSituacion = idSituacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoSituacion")
	public TipoSituacion getTipoSituacion() {
		return this.tipoSituacion;
	}

	public void setTipoSituacion(TipoSituacion tipoSituacion) {
		this.tipoSituacion = tipoSituacion;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "sigla", length = 20)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "idTipoContrato")
	public Integer getIdTipoContrato() {
		return this.idTipoContrato;
	}

	public void setIdTipoContrato(Integer idTipoContrato) {
		this.idTipoContrato = idTipoContrato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "situacionByIdSituacionFinal")
	public List<Log> getLogsForIdSituacionFinal() {
		return this.logsForIdSituacionFinal;
	}

	public void setLogsForIdSituacionFinal(List<Log> logsForIdSituacionFinal) {
		this.logsForIdSituacionFinal = logsForIdSituacionFinal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "situacion")
	public List<Agente> getAgentes() {
		return this.agentes;
	}

	public void setAgentes(List<Agente> agentes) {
		this.agentes = agentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "situacionByIdSituacionInicial")
	public List<Log> getLogsForIdSituacionInicial() {
		return this.logsForIdSituacionInicial;
	}

	public void setLogsForIdSituacionInicial(List<Log> logsForIdSituacionInicial) {
		this.logsForIdSituacionInicial = logsForIdSituacionInicial;
	}

}
