package birra.modelo.dominioInterno;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMovimiento generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "TipoMovimiento", schema = "dbo", catalog = "rrhh")
public class TipoMovimiento implements java.io.Serializable {

	private int idTipoMovimiento;
	private String descripcion;
	private List<Log> logs = new ArrayList<Log>();

	public TipoMovimiento() {
	}

	public TipoMovimiento(int idTipoMovimiento) {
		this.idTipoMovimiento = idTipoMovimiento;
	}

	public TipoMovimiento(int idTipoMovimiento, String descripcion, List<Log> logs) {
		this.idTipoMovimiento = idTipoMovimiento;
		this.descripcion = descripcion;
		this.logs = logs;
	}

	@Id
	@Column(name = "idTipoMovimiento", unique = true, nullable = false)
	public int getIdTipoMovimiento() {
		return this.idTipoMovimiento;
	}

	public void setIdTipoMovimiento(int idTipoMovimiento) {
		this.idTipoMovimiento = idTipoMovimiento;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMovimiento")
	public List<Log> getLogs() {
		return this.logs;
	}

	public void setLogs(List<Log> logs) {
		this.logs = logs;
	}

}
