package birra.modelo.dominioInterno;

// Generated 19/07/2017 10:20:55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoContrato generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "TipoContrato", schema = "dbo", catalog = "rrhh")
public class TipoContrato implements java.io.Serializable {

	private int idTipoContrato;
	private String descripcion;

	public TipoContrato() {
	}

	public TipoContrato(int idTipoContrato, String descripcion) {
		this.idTipoContrato = idTipoContrato;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "idTipoContrato", unique = true, nullable = false)
	public int getIdTipoContrato() {
		return this.idTipoContrato;
	}

	public void setIdTipoContrato(int idTipoContrato) {
		this.idTipoContrato = idTipoContrato;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
