package birra.modelo.dominioInterno;

import java.util.ArrayList;

// Generated 19/07/2017 10:20:55 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDependencia generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "TipoDependencia", schema = "dbo", catalog = "rrhh")
public class TipoDependencia implements java.io.Serializable {

	private int idTipoDependencia;
	private String descripcion;
	private List<Dependencia> dependencias = new ArrayList<Dependencia>();

	public TipoDependencia() {
	}

	public TipoDependencia(int idTipoDependencia, String descripcion) {
		this.idTipoDependencia = idTipoDependencia;
		this.descripcion = descripcion;
	}

	public TipoDependencia(int idTipoDependencia, String descripcion,
			List<Dependencia> dependencias) {
		this.idTipoDependencia = idTipoDependencia;
		this.descripcion = descripcion;
		this.dependencias = dependencias;
	}

	@Id
	@Column(name = "idTipoDependencia", unique = true, nullable = false)
	public int getIdTipoDependencia() {
		return this.idTipoDependencia;
	}

	public void setIdTipoDependencia(int idTipoDependencia) {
		this.idTipoDependencia = idTipoDependencia;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDependencia")
	public List<Dependencia> getDependencias() {
		return this.dependencias;
	}

	public void setDependencias(List<Dependencia> dependencias) {
		this.dependencias = dependencias;
	}

}
