package birra.modelo.dominioInterno;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDocumento generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "TipoDocumento", schema = "dbo", catalog = "rrhh")
public class TipoDocumento implements java.io.Serializable {

	private int idTipoDoc;
	private String descripcion;
	private List<Agente> agentes = new ArrayList<Agente>();

	public TipoDocumento() {
	}

	public TipoDocumento(int idTipoDoc) {
		this.idTipoDoc = idTipoDoc;
	}

	public TipoDocumento(int idTipoDoc, String descripcion, List<Agente> agentes) {
		this.idTipoDoc = idTipoDoc;
		this.descripcion = descripcion;
		this.agentes = agentes;
	}

	@Id
	@Column(name = "idTipoDoc", unique = true, nullable = false)
	public int getIdTipoDoc() {
		return this.idTipoDoc;
	}

	public void setIdTipoDoc(int idTipoDoc) {
		this.idTipoDoc = idTipoDoc;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDocumento")
	public List<Agente> getAgentes() {
		return this.agentes;
	}

	public void setAgentes(List<Agente> agentes) {
		this.agentes = agentes;
	}

}
