package birra.modelo.dominioInterno;

import java.util.ArrayList;

// Generated 19/07/2017 10:20:55 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoSituacion generated by hbm2java
 */
@SuppressWarnings({ "serial", "unused" })
@Entity
@Table(name = "TipoSituacion", schema = "dbo", catalog = "rrhh")
public class TipoSituacion implements java.io.Serializable {

	private int idTipoSituacion;
	private String descripcion;
	private List<Situacion> situacions = new ArrayList<Situacion>();

	public TipoSituacion() {
	}

	public TipoSituacion(int idTipoSituacion, String descripcion) {
		this.idTipoSituacion = idTipoSituacion;
		this.descripcion = descripcion;
	}

	public TipoSituacion(int idTipoSituacion, String descripcion, List<Situacion> situacions) {
		this.idTipoSituacion = idTipoSituacion;
		this.descripcion = descripcion;
		this.situacions = situacions;
	}

	@Id
	@Column(name = "idTipoSituacion", unique = true, nullable = false)
	public int getIdTipoSituacion() {
		return this.idTipoSituacion;
	}

	public void setIdTipoSituacion(int idTipoSituacion) {
		this.idTipoSituacion = idTipoSituacion;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoSituacion")
	public List<Situacion> getSituacions() {
		return this.situacions;
	}

	public void setSituacions(List<Situacion> situacions) {
		this.situacions = situacions;
	}

}
