package birra.modelo.dominioInterno;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoUsuario generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "TipoUsuario", schema = "dbo", catalog = "rrhh")
public class TipoUsuario implements java.io.Serializable {

	private int idTipoUsuario;
	private String descripcion;
	private List<UsuarioHabilitado> usuarioHabilitados = new ArrayList<UsuarioHabilitado>();

	public TipoUsuario() {
	}

	public TipoUsuario(int idTipoUsuario, String descripcion) {
		this.idTipoUsuario = idTipoUsuario;
		this.descripcion = descripcion;
	}

	public TipoUsuario(int idTipoUsuario, String descripcion,
			List<UsuarioHabilitado> usuarioHabilitados) {
		this.idTipoUsuario = idTipoUsuario;
		this.descripcion = descripcion;
		this.usuarioHabilitados = usuarioHabilitados;
	}

	@Id
	@Column(name = "idTipoUsuario", unique = true, nullable = false)
	public int getIdTipoUsuario() {
		return this.idTipoUsuario;
	}

	public void setIdTipoUsuario(int idTipoUsuario) {
		this.idTipoUsuario = idTipoUsuario;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUsuario")
	public List<UsuarioHabilitado> getUsuarioHabilitados() {
		return this.usuarioHabilitados;
	}

	public void setUsuarioHabilitados(List<UsuarioHabilitado> usuarioHabilitados) {
		this.usuarioHabilitados = usuarioHabilitados;
	}

}
