package birra.modelo.dominioInterno;

import java.util.ArrayList;

// Generated 19/07/2017 10:20:55 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Titulo generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Titulo", schema = "dbo", catalog = "rrhh")
public class Titulo implements java.io.Serializable {

	private int idTitulo;
	private String descripcion;
	private List<Agente> agentes = new ArrayList<Agente>();

	public Titulo() {
	}

	public Titulo(int idTitulo) {
		this.idTitulo = idTitulo;
	}

	public Titulo(int idTitulo, String descripcion, List<Agente> agentes) {
		this.idTitulo = idTitulo;
		this.descripcion = descripcion;
		this.agentes = agentes;
	}

	@Id
	@Column(name = "idTitulo", unique = true, nullable = false)
	public int getIdTitulo() {
		return this.idTitulo;
	}

	public void setIdTitulo(int idTitulo) {
		this.idTitulo = idTitulo;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titulo")
	public List<Agente> getAgentes() {
		return this.agentes;
	}

	public void setAgentes(List<Agente> agentes) {
		this.agentes = agentes;
	}

}
