package birra.modelo.dominioInterno;

// Generated 19/07/2017 10:20:55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UsuarioHabilitado generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "UsuarioHabilitado", schema = "dbo", catalog = "rrhh")
public class UsuarioHabilitado implements java.io.Serializable {

	private int legajo;
	private TipoUsuario tipoUsuario;
	private Agente agente;

	public UsuarioHabilitado() {
	}

	public UsuarioHabilitado(TipoUsuario tipoUsuario, Agente agente) {
		this.tipoUsuario = tipoUsuario;
		this.agente = agente;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "agente"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "legajo", unique = true, nullable = false)
	public int getLegajo() {
		return this.legajo;
	}

	public void setLegajo(int legajo) {
		this.legajo = legajo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoUsuario", nullable = false)
	public TipoUsuario getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Agente getAgente() {
		return this.agente;
	}

	public void setAgente(Agente agente) {
		this.agente = agente;
	}

}
